"""HGDN fused CUDA kernels and safe fallbacks."""

from .ops import (
    HAS_FLA_GATED_DELTA_RULE,
    extension_loaded,
    extension_status,
    fla_chunk_gated_delta_rule_compile_visible,
    fla_chunk_gated_delta_rule_direct,
    fla_chunk_gated_delta_rule_direct_fused_gate_norm,
    fused_packed_qkv_conv,
    fused_packed_qkv_conv_aten_backward,
    fused_packed_qkv_conv_aten_weight_backward,
    fused_packed_qkv_frontend,
    fused_packed_qkv_split_l2norm,
    fused_rmsnorm_silu_gate,
    frontend_preact_silu_split_l2norm_nct,
    packed_qkv_frontend_compile_visible,
    packed_qkv_split_l2norm_compile_visible,
)
from .reference import (
    packed_qkv_conv_reference,
    packed_qkv_frontend_reference,
    packed_qkv_split_l2norm_backward_reference,
    packed_qkv_split_l2norm_reference,
    preact_silu_split_l2norm_nct_backward_reference,
    preact_silu_split_l2norm_nct_reference,
    rmsnorm_silu_gate_reference,
)

__all__ = [
    "extension_loaded",
    "extension_status",
    "HAS_FLA_GATED_DELTA_RULE",
    "fla_chunk_gated_delta_rule_compile_visible",
    "fla_chunk_gated_delta_rule_direct",
    "fla_chunk_gated_delta_rule_direct_fused_gate_norm",
    "fused_packed_qkv_conv",
    "fused_packed_qkv_conv_aten_backward",
    "fused_packed_qkv_conv_aten_weight_backward",
    "fused_packed_qkv_frontend",
    "fused_packed_qkv_split_l2norm",
    "fused_rmsnorm_silu_gate",
    "frontend_preact_silu_split_l2norm_nct",
    "packed_qkv_frontend_compile_visible",
    "packed_qkv_split_l2norm_compile_visible",
    "packed_qkv_conv_reference",
    "packed_qkv_frontend_reference",
    "packed_qkv_split_l2norm_backward_reference",
    "packed_qkv_split_l2norm_reference",
    "preact_silu_split_l2norm_nct_reference",
    "preact_silu_split_l2norm_nct_backward_reference",
    "rmsnorm_silu_gate_reference",
]
